language: node_js

node_js:
  - '8'
  - '10'

sudo: false

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
  - travis_retry npm install -g npm@latest

script:
  - npm run lint
